### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by nkstnkst** [zoom/zoomapps-advancedsample-react#15]
I followed the instructions. When I try to add the app, this error happens. Looks like it's missing a "state" param in the URL. How can I fix it?
```
backend_1   | ZOOM OAUTH REDIRECT HANDLER  ============================================== 
backend_1   | 
backend_1   | 1. Handling redirect from zoom.us with code and state following authentication to Zoom 
backend_1   | 
backend_1   | 1a. code param exists: 3ZDQH98oh8J0YKDVCU6SY-E3rQ2m9T3Rg 
backend_1   | 
backend_1   | GET /api/zoomapp/auth?code=3ZDQH98oh8J0YKDVCU6SY-E3rQ2m9T3Rg 400 1.282 ms - 1126
backend_1   | Error: Invalid state parameter
backend_1   |     at auth (/home/node/app/api/zoomapp/controller.js:173:21)
backend_1   |     at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
backend_1   |     at next (/home/node/app/node_modules/express/lib/router/route.js:149:13)
backend_1   |     at Route.dispatch (/home/node/app/node_modules/express/lib/router/route.js:119:3)
backend_1   |     at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
backend_1   |     at /home/node/app/node_modules/express/lib/router/index.js:284:15
backend_1   |     at Function.process_params (/home/node/app/node_modules/express/lib/router/index.js:346:12)
backend_1   |     at next (/home/node/app/node_modules/express/lib/router/index.js:280:10)
backend_1   |     at Function.handle (/home/node/app/node_modules/express/lib/router/index.js:175:3)
backend_1   |     at router (/home/node/app/node_modules/express/lib/router/index.js:47:12)
```

**Comment by DerekCL** [comment]
Can Confirm the above. Get a 302 Found on /api/zoomapp/install but then get a invalid URL on

Invalid redirect: https://numbers-ngrok-free.app/api/zoomapp/auth (4,700)

**Comment by RealmX1** [comment]
The same issue still poersist
