### ISSUE TITLE
Fetch request to Zoom artifacts failing during installation

### ISSUE THREAD

**Issue by anuragsoulside** [zoom/zoomapps-advancedsample-react#4]
### Stacktrace

```
[+] Building 304.6s (13/19)                                                                           
 => [zoomapps-advancedsample-react-frontend internal] load build definition from Dockerfile      0.0s
 => => transferring dockerfile: 32B                                                              0.0s
 => [zoomapps-advancedsample-react-backend internal] load build definition from Dockerfile       0.0s
 => => transferring dockerfile: 32B                                                              0.0s
 => [zoomapps-advancedsample-react-frontend internal] load .dockerignore                         0.0s
 => => transferring context: 34B                                                                 0.0s
 => [zoomapps-advancedsample-react-backend internal] load .dockerignore                          0.0s
 => => transferring context: 34B                                                                 0.0s
 => [zoomapps-advancedsample-react-frontend internal] load metadata for docker.io/library/node:  1.1s
 => [zoomapps-advancedsample-react-frontend 1/7] FROM docker.io/library/node:16@sha256:8ef06c51  0.0s
 => [zoomapps-advancedsample-react-frontend internal] load build context                         0.0s
 => => transferring context: 1.40kB                                                              0.0s
 => [zoomapps-advancedsample-react-backend internal] load build context                          0.0s
 => => transferring context: 1.13kB                                                              0.0s
 => CACHED [zoomapps-advancedsample-react-frontend 2/7] WORKDIR /home/node/app                   0.0s
 => CACHED [zoomapps-advancedsample-react-backend 3/7] COPY package*.json ./                     0.0s
 => ERROR [zoomapps-advancedsample-react-backend 4/7] RUN npm install                          303.1s
 => CACHED [zoomapps-advancedsample-react-frontend 3/7] COPY package*.json ./                    0.0s
 => CANCELED [zoomapps-advancedsample-react-frontend 4/7] RUN npm install                      303.2s
------                                                                                                
 > [zoomapps-advancedsample-react-backend 4/7] RUN npm install:
#0 303.0 npm notice 
#0 303.0 npm notice New major version of npm available! 8.19.3 -> 9.6.1
#0 303.0 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.1>
#0 303.0 npm notice Run `npm install -g npm@9.6.1` to update!
#0 303.0 npm notice 
#0 303.0 npm ERR! code ECONNREFUSED
#0 303.0 npm ERR! syscall connect
#0 303.0 npm ERR! errno ECONNREFUSED
#0 303.0 npm ERR! FetchError: request to https://artifacts.corp.zoom.us/artifactory/api/npm/zoom-npm-virtual/yallist/-/yallist-4.0.0.tgz failed, reason: connect ECONNREFUSED 10.20.12.20:443
#0 303.0 npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
#0 303.0 npm ERR!     at ClientRequest.emit (node:events:513:28)
#0 303.0 npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:494:9)
#0 303.0 npm ERR!     at TLSSocket.emit (node:events:525:35)
#0 303.0 npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
#0 303.0 npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
#0 303.0 npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#0 303.0 npm ERR!  FetchError: request to https://artifacts.corp.zoom.us/artifactory/api/npm/zoom-npm-virtual/yallist/-/yallist-4.0.0.tgz failed, reason: connect ECONNREFUSED 10.20.12.20:443
#0 303.0 npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
#0 303.0 npm ERR!     at ClientRequest.emit (node:events:513:28)
#0 303.0 npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:494:9)
#0 303.0 npm ERR!     at TLSSocket.emit (node:events:525:35)
#0 303.0 npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
#0 303.0 npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
#0 303.0 npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
#0 303.0 npm ERR!   code: 'ECONNREFUSED',
#0 303.0 npm ERR!   errno: 'ECONNREFUSED',
#0 303.0 npm ERR!   syscall: 'connect',
#0 303.0 npm ERR!   address: '10.20.12.20',
#0 303.0 npm ERR!   port: 443,
#0 303.0 npm ERR!   type: 'system'
#0 303.0 npm ERR! }
#0 303.0 npm ERR! 
#0 303.0 npm ERR! If you are behind a proxy, please make sure that the
#0 303.0 npm ERR! 'proxy' config is set properly.  See: 'npm help config'
#0 303.0 
#0 303.0 npm ERR! A complete log of this run can be found in:
#0 303.0 npm ERR!     /root/.npm/_logs/2023-03-14T15_48_41_978Z-debug-0.log
------
failed to solve: executor failed running [/bin/sh -c npm install]: exit code: 1
```

**Comment by anuragsoulside** [comment]
@joeyu23 Can you please take a look at this **urgently**? I think your commit on Jan 23 is breaking the installation. Thank you.

**Comment by SalehBagheri** [comment]
I have the same problem :( Connection timeout for the package.
