### ISSUE TITLE
\install fails with 500 invalid key length

### ISSUE THREAD

**Issue by tevslin** [zoom/zoomapps-advancedsample-react#5]
The app is installed in zoom client after the failure but gets the same error when opened. this is on Windows 11. Docker running in WSL 2.
message in the log is below

 2c. Save the tokens in the store so we can look them up when the Zoom App is opened
2023-04-08 16:59:59 zoomapps-advancedsample-react-backend-1   | GET /api/zoomapp/auth?code=tlUqPQn5YMmSBowi3bXT-WWXJ4fKcHH7Q&state=cFTjqJikctPmoMRS6MKfZoVtHatF8jUMni7CesE%2FBbU%3D.651db82b3659125f7de8e3a3fb5b0130b31ec0f265318d4599be890fd9b7a6442f20c382971e7eeffa310d49ea4e8bab705b7a5ee1e79fc2a04854f0fa35dff7 500 703.321 ms - 777
2023-04-08 16:59:59 zoomapps-advancedsample-react-backend-1   | RangeError: Invalid key length
2023-04-08 16:59:59 zoomapps-advancedsample-react-backend-1   |     at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
2023-04-08 16:59:59 zoomapps-advancedsample-react-backend-1   |     at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
2023-04-08 16:59:59 zoomapps-advancedsample-react-backend-1   |     at new Cipheriv (node:internal/crypto/cipher:243:3)
2023-04-08 16:59:59 zoomapps-advancedsample-react-backend-1   |     at Object.createCipheriv (node:crypto:138:10)
2023-04-08 16:59:59 zoomapps-advancedsample-react-backend-1   |     at Object.afterSerialization (/home/node/app/util/encrypt.js:6:24)
2023-04-08 16:59:59 zoomapps-advancedsample-react-backend-1   |     at Object.upsertUser (/home/node/app/util/store.js:49:15)
2023-04-08 16:59:59 zoomapps-advancedsample-react-backend-1   |     at auth (/home/node/app/api/zoomapp/controller.js:218:19)
2023-04-08 16:59:59 zoomapps-advancedsample-react-backend-1   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by focalsolution** [comment]
You need to generate new `REDIS_ENCRYPTION_KEY` and put it in .env as the one provided in .env.example is incorrect.

```
$ openssl rand -hex 16
```
